requires 'Mojolicious', '==9.25';
requires 'Mojo::Pg', '==4.27';
requires 'Net::Statsd', '==0.12';
requires 'Minion', '==10.24';
requires 'Twitter::API', '==1.0006';
requires 'String::CamelCase', '==0.04';
requires 'Future::AsyncAwait', '==0.58';
requires 'YAML::Tiny', '==1.73';
requires 'Object::Container', '==0.14';
