requires 'Moo';
requires 'Twitter::API';
requires 'YAML::Tiny';
requires 'Term::ReadLine::Gnu';
requires 'Pry';
requires 'Net::OAuth';
requires 'Furl';
requires 'Getopt::Compact';
requires 'Parallel::ForkManager';
requires 'Redis';
requires 'Log::Dispatch';
requires 'Clone';
requires 'JSON';
requires 'TokyoCabinet', url => 'https://dbmx.net/tokyocabinet/perlpkg/tokyocabinet-perl-1.34.tar.gz';
requires 'Net::Statsd';
