version: '3'

services:
  app:
    build: .
    command: bash
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    depends_on:
    - selenium
  selenium:
    image: selenium/standalone-firefox:latest
    environment:
      TZ: Asia/Tokyo
    volumes: [/dev/shm:/dev/shm]
