version: '3'

services:
  app:
    restart: always
    build: .
    # command: carton exec perl devourer fetch twitter -d
    volumes:
    - .:/app
    - ./.carmel_cache:/home/app/.carmel
    ports:
    - 3000:3000
    stdin_open: true
    tty: true
    depends_on: [db]
  db:
    restart: always
    image: postgres:14-alpine
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    volumes: ['./postgres14:/var/lib/postgresql/data']
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
